# Generated by Django 4.1.6 on 2023-02-21 07:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('full_name', models.CharField(max_length=255)),
                ('company', models.CharField(max_length=255)),
                ('contact_phone', models.CharField(blank=True, max_length=20, null=True)),
                ('company_site', models.URLField(blank=True, null=True)),
                ('country', models.CharField(max_length=255)),
                ('communication', models.CharField(blank=True, max_length=255, null=True)),
                ('client_id', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('client_secret', models.CharField(max_length=255)),
                ('token', models.CharField(blank=True, max_length=255, null=True)),
                ('structure', models.CharField(max_length=255)),
                ('auth_code', models.CharField(blank=True, max_length=255, null=True)),
                ('allow_changes', models.BooleanField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
