# Generated by Django 4.1.6 on 2023-02-24 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='last_4_digits',
            field=models.CharField(blank=True, max_length=4, null=True),
        ),
    ]
