# Generated by Django 4.1.6 on 2023-02-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_creditcard_last_4_digits'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='card_type',
            field=models.CharField(choices=[('visa', 'visa'), ('mastercard', 'mastercard'), ('discover', 'discover'), ('american-express', 'american-express'), ('Other', 'Other')], max_length=20),
        ),
    ]
