# Generated by Django 4.1.6 on 2023-02-26 02:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0003_plan_duration_alter_subscription_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='plan',
            name='description',
        ),
        migrations.AddField(
            model_name='plan',
            name='messages_limit',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
