# Generated by Django 4.1.6 on 2023-02-26 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0004_remove_plan_description_plan_messages_limit'),
    ]

    operations = [
        migrations.CreateModel(
            name='userdata',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Isim', models.CharField(blank=True, max_length=255, null=True)),
                ('Soyisim', models.CharField(blank=True, max_length=255, null=True)),
                ('SmsIzin', models.BooleanField(blank=True, null=True)),
                ('CepTelefonu', models.CharField(blank=True, max_length=255, null=True)),
                ('UyeID', models.IntegerField(blank=True, null=True)),
                ('products_1', models.CharField(blank=True, max_length=255, null=True)),
                ('products_2', models.CharField(blank=True, max_length=255, null=True)),
                ('products_3', models.CharField(blank=True, max_length=255, null=True)),
                ('products_4', models.CharField(blank=True, max_length=255, null=True)),
                ('products_5', models.CharField(blank=True, max_length=255, null=True)),
                ('products_6', models.CharField(blank=True, max_length=255, null=True)),
                ('products_7', models.CharField(blank=True, max_length=255, null=True)),
                ('products_8', models.CharField(blank=True, max_length=255, null=True)),
                ('products_9', models.CharField(blank=True, max_length=255, null=True)),
                ('products_10', models.CharField(blank=True, max_length=255, null=True)),
                ('products_11', models.CharField(blank=True, max_length=255, null=True)),
                ('products_12', models.CharField(blank=True, max_length=255, null=True)),
                ('products_13', models.CharField(blank=True, max_length=255, null=True)),
                ('products_14', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
