# Generated by Django 4.1.6 on 2023-02-27 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0007_newdata_delete_userdata'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='newdata',
            name='id',
        ),
        migrations.AddField(
            model_name='newdata',
            name='created_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='newdata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='newdata',
            name='UyeID',
            field=models.IntegerField(default=0, primary_key=True, serialize=False),
        ),
    ]
