# Generated by Django 4.1.6 on 2023-02-28 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0010_newdata_user_fetch_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fetch_data',
            name='uni_code',
        ),
        migrations.RemoveField(
            model_name='fetch_data',
            name='website_link',
        ),
    ]
