# Generated by Django 4.1.6 on 2023-02-28 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dashboard', '0011_remove_fetch_data_uni_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='fetch_data',
            name='uni_code',
            field=models.CharField(blank=True, default='<tem:UyeKodu>1MAG6YAT4FFLA1FG5Y1UJFQE10JK6T</tem:UyeKodu>', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='fetch_data',
            name='website_link',
            field=models.CharField(blank=True, default='http://karumrouge.com/', max_length=255, null=True),
        ),
    ]
